# --- Spring Application Name ---
spring.application.name=ecommerce-backend-local

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- JWT Configuration for Local Development ---
jwt.secret=SUxvdmVCYW5nbGFkZXNoSXRJc0FCZWF1dGlmdWxsQ291bnRyeQ==
jwt.expirationMs=86400000

# --- Server Port for Local Development ---
server.port=8080

# --- CORS Configuration for Local Development (for Angular Frontend) ---
spring.web.cors.allowed-origins=http://localhost:4200
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

# --- Springdoc OpenAPI (Swagger) Configuration ---
# Specify the packages where Springdoc should look for @RestController classes
springdoc.packages-to-scan=com.ecommerce.eshop
# Or, if you want to be very specific about controllers:
# springdoc.packages-to-scan=com.ecommerce.eshop.authmodule.controller
